name: Check mssql

on:
  pull_request

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run the action
      uses: potatoqualitee/mssqlsuite@v1
      with:
        install: sqlengine, sqlpackage

    - name: Run sqlclient
      run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "SELECT @@version;"
      
    - name: Create Database
      run: |
        sqlcmd -S localhost -U sa -P dbatools.I0 -i scripts/database.sql
        
    - name: Create Tables
      run: sqlcmd -S localhost -U sa -P dbatools.I0 -d FUDormitory -i scripts/table.sql
    
    - name: Create Triggers
      run: sqlcmd -S localhost -U sa -P dbatools.I0 -d FUDormitory -i scripts/triggers.sql
      
    - name: Insert Data
      run: sqlcmd -S localhost -U sa -P dbatools.I0 -d FUDormitory -i scripts/data.sql
      
    - name: Run Tests
      run: sqlcmd -S localhost -U sa -P dbatools.I0 -d FUDormitory -i scripts/test.sql
